#!/bin/bash
###
### shutdown - service hook for shutting down  services; called by /etc/init.d/services_startup
###

# Load environment variables
HOME=/services/medusa
. $HOME/.bashrc

# Stop Tomcat
$HOME/bin/stop-tomcat

# Stop PostgreSQL
$HOME/bin/stop-postgres

# Stop ClamAV daemon
#$HOME/bin/stop-clamd

# Stop whatever
